# Generated by Django 4.2.13 on 2024-06-14 13:59

from django.db import migrations, models
import django.db.models.functions.text
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNumber', models.CharField(help_text='Enter customer number', max_length=200, unique=True)),
                ('memberType', models.CharField(choices=[('ST', 'Starter'), ('AD', 'Advanced')], default='ST', help_text='Enter member type', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter device name', max_length=100)),
                ('value', models.FloatField(help_text='Enter device value')),
                ('units', models.CharField(help_text='Enter device units', max_length=10)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('deviceStatus', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', help_text='Enter device status', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='GDPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter first name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number', max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Enter installation address', max_length=200, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelType', models.CharField(help_text='Enter panel type', max_length=100)),
                ('brand', models.CharField(help_text='Enter panel brand', max_length=100)),
                ('maxPower', models.DecimalField(decimal_places=2, help_text='Enter panel max power', max_digits=5)),
                ('orientation', models.CharField(help_text='Enter panel orientation', max_length=100)),
                ('year', models.IntegerField(help_text='Enter panel year')),
            ],
        ),
        migrations.AddConstraint(
            model_name='installation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('address'), name='installation_address_case_insensitive_unique', violation_error_message='An installation with that address already exists.'),
        ),
    ]
