# Generated by Django 4.2.13 on 2024-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohmtimize', '0002_billing_consumption_gridexchange_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='postcode',
            field=models.CharField(default='0000', help_text='Enter postcode', max_length=4),
        ),
    ]
