# Generated by Django 4.2.13 on 2024-06-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohmtimize', '0007_alter_device_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceStatus',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', help_text='Enter device status <br><br>', max_length=7),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Enter device name <br><br>', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='units',
            field=models.CharField(help_text='Enter device units <br><br>', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='value',
            field=models.FloatField(default=0, help_text='Enter device value <br><br>'),
        ),
    ]
