# Generated by Django 4.2.13 on 2024-06-24 09:13

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ohmtimize', '0008_alter_device_devicestatus_alter_device_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdpr',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='gdpr',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='gdpr',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='gdpr_user_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='password',
            field=models.CharField(help_text='Enter password', max_length=15),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='gdpr_user_permissions_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='gdpr',
            name='username',
            field=models.CharField(default='username', max_length=10),
        ),
    ]
