# Generated by Django 4.2.13 on 2024-06-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohmtimize', '0009_alter_gdpr_options_alter_gdpr_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdpr',
            managers=[
            ],
        ),
    ]
