# Generated by Django 4.2.13 on 2024-06-28 09:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohmtimize', '0010_alter_gdpr_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdpr',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
