# Generated by Django 4.2.13 on 2024-07-01 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohmtimize', '0011_alter_gdpr_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GDPR',
        ),
    ]
